Add files via upload
LukshaMaria/Projects-Webix pull request #4
Opened 2022-07-14 10:08 UTC by LukshaMaria

2022-07-14 16:11 UTC, HelgaListopad requested changes

2022-07-14 16:11 UTC, HelgaListopad commented on task-webix.html
> +					view: "menu", subMenuPos: "down", layout: "y", data: [{ value: "Profile", css: "webix_transparent", type: "icon", icon: "mdi mdi-account", submenu: ["Settings", "Log Out"] }],
В задании написано, что popup должен открываться при клике на кнопку. 
Замена интересная, но меню это всё же не кнопка (и стили у него не те) - важно разобраться, как сделать точно по заданию.
https://slides.com/sinode/1-2-webix-basics-interaction-with-users#/13/0/1
https://docs.webix.com/desktop__popup.html#creatingpopupmenu

2022-07-14 16:11 UTC, HelgaListopad commented on task-webix.html
> +								}
Можно сократить код, избавившись от `result` и не вызывая несколько раз `$$("form")` (такой вызов - это метод, который возвращает один и тот же объект, поэтому здесь достаточно получить его один раз)
```js
const form = $$("form");
if (form.validate()) { ... }
else { ... }
```

2022-07-14 16:11 UTC, HelgaListopad commented on task-webix.html
> +									webix.message("Information don't add to datatable!");
don't add -> wasn't added

2022-07-14 16:11 UTC, HelgaListopad commented on task-webix.html
> +									webix.message("Information add to datatable!");
add -> was added

2022-07-14 16:11 UTC, HelgaListopad commented on task-webix.html
> +										$$("form1").clearValidation();
Здесь тоже можно вынести в переменую `form`

2022-07-14 16:11 UTC, HelgaListopad commented on task-webix.html
> +				},
Попробуй заменить на стрелочные ф-ции: здесь сразу возвращаются простые выражения и не нужно обращаться к `this`

2022-07-14 16:12 UTC, HelgaListopad commented on task-webix.html
>  		var toolbar = {
Лучше всего вообще избавиться от `var` в коде и использовать только `let`/`const` в зависимости от ситуации

2022-07-15 10:32 UTC, LukshaMaria commented on task-webix.html
>  		var toolbar = {
fixed

2022-07-15 10:41 UTC, LukshaMaria commented on task-webix.html
> +				},
fixed

2022-07-15 10:43 UTC, LukshaMaria commented on task-webix.html
> +									webix.message("Information add to datatable!");
fixed

2022-07-15 10:43 UTC, LukshaMaria commented on task-webix.html
> +									webix.message("Information don't add to datatable!");
fixed

2022-07-15 10:50 UTC, LukshaMaria commented on task-webix.html
> +								}
fixed

2022-07-15 10:50 UTC, LukshaMaria commented on task-webix.html
> +										$$("form1").clearValidation();
fixed

2022-07-15 11:02 UTC, HelgaListopad commented on task-webix.html
>  		var toolbar = {
Не совсем
> в зависимости от ситуации

Для тех переменных, значения которых ты не планируешь менять, уместнее `const`

2022-07-15 11:07 UTC, HelgaListopad commented on task-webix.html
> +							view: "button", value: "Add new", css: "webix_primary", click: function () {
Я пропустила это, но так как data binding подволяет и добавлять новые, и редактировать существующие записи, кнопку лучше переименовать в более общее "Save"

2022-07-15 15:03 UTC, LukshaMaria commented on task-webix.html
> +								}
add 
const form = $$("form1");

update
console.log(form.validate());
if (form.validate()) {
form.save();
}

2022-07-15 15:05 UTC, LukshaMaria commented on task-webix.html
> +										$$("form1").clearValidation();
add
const form = $$("form1");

update
form .clear(); 
form .clearValidation();

2022-07-15 15:10 UTC, LukshaMaria commented on task-webix.html
>  		var toolbar = {
Update type let, string 16, 32, 40, 41

2022-07-15 15:15 UTC, LukshaMaria commented on task-webix.html
> +							view: "button", value: "Add new", css: "webix_primary", click: function () {
fixed

2022-07-15 16:26 UTC, LukshaMaria commented on task-webix.html
> +					view: "menu", subMenuPos: "down", layout: "y", data: [{ value: "Profile", css: "webix_transparent", type: "icon", icon: "mdi mdi-account", submenu: ["Settings", "Log Out"] }],
fixed

2022-07-15 16:40 UTC, HelgaListopad commented on task-webix.html
> +		const popup1 = webix.ui({
Перемести это в конец, до или после ещё одного `webix.ui`

Лучше разделять переменные с конфигом и инициализированные объекты UI, чтобы не было путаницы
Кроме того, если для инита используется `webix.ready`, то лучше заворачивать туда инициализацию всех объектов
Должно получиться
```
const toolbar = {};
const menu = {};
const table = {};
const form = {};

webix.ready(() => {
   const popup = webix.ui({ /* popup config */ });
   webix.ui({ /*  main UI */ });
   // other methods, e.g. data binding
});

2022-07-15 16:51 UTC, LukshaMaria commented on task-webix.html
> +		const popup1 = webix.ui({
fixed

2022-07-15 16:57 UTC, HelgaListopad approved these changes

2022-07-15 16:58 UTC, merged