Add files via upload
LukshaMaria/Projects-Webix pull request #5
Opened 2022-07-19 19:59 UTC by LukshaMaria

Task 1-3, the code was split onto separete files.

2022-07-20 13:45 UTC, HelgaListopad requested changes

2022-07-20 13:45 UTC, HelgaListopad commented on modules/charts.js
> +    url: "http://localhost/Projects-Webix/data/users.js",
Здесь и **везде**, где грузятся данные: нельзя писать абсолютные пути для файлов, которые вложены в тот же проект - нужно переделать на относительные внутри проекта. Сработает `"./data/users.js"`
У нас с тобой под localhost разная файловая система, и "localhost/Projects-Webix" для меня не существует

2022-07-20 13:45 UTC, HelgaListopad commented on main.js
> +    $$("form1").bind("datatable1");
`bind` нужно убрать, так как в этом задании ты сама пишешь логику сохранения данных для тамблицы и формы

2022-07-20 13:45 UTC, HelgaListopad commented on main.js
> +        { id: "Products", cols: [producttable] },
Мне не очень нравится, что в main.js используются переменные, которых в самом файле нет.
Либо нужно всё же перевести всё на es6 импорты (тогда ты в main будешь импортировать всё остальное и все переменные будут доступны в явном виде), либо код из main.js всё же перенести в основной html-файл

2022-07-20 13:45 UTC, HelgaListopad commented on main.js
> +    const popup1 = webix.ui({
Если переменная `popup1` нигде не используется, можно не объявлять её и просто сразу инитить popup как `webix.ui({ ... })`

2022-07-20 13:45 UTC, HelgaListopad commented on main.js
> +        { id: "Users", cols: [usertable, userchart] },
На иллюстрации `rows`

2022-07-20 13:45 UTC, HelgaListopad commented on modules/forms.js
> +            margin: 5, cols: [
Оставь только кнопки Save и Clear

2022-07-20 13:45 UTC, HelgaListopad commented on modules/forms.js
> +                    view: "button", value: "Save", click: function () {
Выдели эту кнопку стилем webix_primary

2022-07-20 13:45 UTC, HelgaListopad commented on modules/forms.js
> +                        }
Для того, чтобы начать это делать, должна сначала успешно пройти валидация полей

2022-07-20 13:45 UTC, HelgaListopad commented on modules/maintable.js
> +            this.remove(id);
`remove` можно заментиь на confirm + remove из кнопки Delete (в задании нет, но есть смысл сохранить такое поведение)
```js
webix.confirm("Do you want to delete this item?", "confirm-warning")
.then(() => {
    this.remove(id);
});
```

2022-07-20 13:45 UTC, HelgaListopad commented on modules/maintable.js
> +    autoConfig: true,
Стоит убрать - `autoConfig` нужен в первую очередь для случая, когда колонки не заданы в явном виде

2022-07-20 13:45 UTC, HelgaListopad commented on modules/maintable.js
> +    topSplit: 2,
Лучше убрать - в задании нет.

Кроме того, обрати внимание, что в колонке Id на закреплённые строки не срабатывает стиль "colls_css" - это тот случай, когда родной стиль (на ячейках появляется `webix_topcell`) перебивает тот, что написан для колонки. Исправляются такие вещи верным css-селектором.

2022-07-20 13:45 UTC, HelgaListopad commented on modules/usertable.js
> +        url: "http://localhost/Projects-Webix/data/users.js",
"./data/users.js"

2022-07-20 13:45 UTC, HelgaListopad commented on modules/usertable.js
> +        view: "datatable",
Здесь по заданию должен быть лист

2022-07-20 13:45 UTC, HelgaListopad commented on modules/usertable.js
> +        cols: [
не хватает поля, через которое можно было бы фильтровать лист (`onTimedKeyPress` => `list.filter()`)

2022-07-20 13:45 UTC, HelgaListopad commented on modules/usertable.js
> +        }
Проверка id сработает здесь, но не очень хороша в целом - это может быть любое число или строка, поэтому лучше сразу учиться другим вариантам.

То же самое можно было бы сделать после загрузки данных в ready, работая с индексом строки, а не с id (id всё равно нужно, чтобы добавить стиль, но найти нужную строку лучше через индекс)
```js
ready() { 
   for (let i = 0; i < 5; i++) {
       const id = this.getIdByIndex(i);
      this.addCss(id, "highlight");       
   }
}

2022-07-20 13:45 UTC, HelgaListopad commented on modules/producttable.js
> +    data: [
загрузи из data/products.js

2022-07-20 13:45 UTC, HelgaListopad commented on modules/maintable.js
> +    url: "http://localhost/Projects-Webix/data/data.js",
./data/data.js

2022-07-20 14:00 UTC, HelgaListopad commented
Дополнительно (попробуй это только после того, как внесёшь все остальные изменения, в том числе переход на ES6 imports)

В разных файлах используются ID виджетов, которых там нет - например, popup c `id: "popup1"` объявлен в одном файле, а обращение к нему через это ID происходит в файле c тулбаром/кнопкой:
```js
// toolbar.js
click() {
     const node = this.getNode();
     $$("popup1").show(node);
}
```

Для любого проекта это не очень удобный и рискованный вариант, так как легко поменять ID в одном месте, упустив где-то ещё.

Чтобы избежать проблем, безопасным варирантом будет создать отдельный файл, откуда будут экспортироваться константы-айдишки, например
```js
export const list_id = "list";
export const popup_id = "popup";

// или единым объектом (примеры ниже для этого случая)
export const globalID = { 
   popup: "popup",
   list: "list"
}

```

Тогда их можно импортировать и переиспользовать во всех других файлах - везде будет одна и та же константа
```js
// main.js
import { globalID } from "/constants.js"
/* ... */
webix.ui({ 
   view: "popup",
   id: globalID.popup
})

```js
// toolbar.js
import { popup_id } from "/constants.js"
/* ... */
click() {
     $$(globalID.popup).show();
}
```

2022-07-20 14:50 UTC, HelgaListopad commented on task-webix.html
> +            background-color: rgb(164, 164, 164);
Здесь лучше возьми цвет header'a таблицы

2022-07-20 18:47 UTC, LukshaMaria commented on modules/charts.js
> +    url: "http://localhost/Projects-Webix/data/users.js",
fixed
Changed files: maintable.js, usertable.js, charts.js

2022-07-20 18:51 UTC, LukshaMaria commented on main.js
> +    $$("form1").bind("datatable1");
fixed

2022-07-20 19:32 UTC, LukshaMaria commented on main.js
> +        { id: "Products", cols: [producttable] },
fixed

2022-07-20 19:35 UTC, LukshaMaria commented on main.js
> +    const popup1 = webix.ui({
fixed

2022-07-20 19:40 UTC, LukshaMaria commented on main.js
> +        { id: "Users", cols: [usertable, userchart] },
В задании было написано 4 ячейки: Multiview should have 4 cells:...

2022-07-20 19:43 UTC, LukshaMaria commented on modules/forms.js
> +            margin: 5, cols: [
fixed

2022-07-20 19:48 UTC, LukshaMaria commented on modules/forms.js
> +                    view: "button", value: "Save", click: function () {
fixed

2022-07-20 19:52 UTC, LukshaMaria commented on modules/maintable.js
> +    autoConfig: true,
fixed

2022-07-20 19:53 UTC, LukshaMaria commented on modules/usertable.js
> +        url: "http://localhost/Projects-Webix/data/users.js",
fixed

2022-07-20 19:53 UTC, LukshaMaria commented on modules/maintable.js
> +    url: "http://localhost/Projects-Webix/data/data.js",
fixed

2022-07-20 20:14 UTC, LukshaMaria commented on task-webix.html
> +            background-color: rgb(164, 164, 164);
fixed

2022-07-20 20:36 UTC, LukshaMaria commented on modules/forms.js
> +                        }
fixed

2022-07-20 20:44 UTC, LukshaMaria commented on modules/maintable.js
> +            this.remove(id);
fixed

2022-07-20 20:50 UTC, LukshaMaria commented on modules/maintable.js
> +    topSplit: 2,
fixed.
Убрала scroll, select,  autoConfig,topSplit и navigation и стиль применился ко всей колонке.

2022-07-21 05:54 UTC, LukshaMaria commented on modules/producttable.js
> +    data: [
fixed

2022-07-21 09:55 UTC, HelgaListopad commented on main.js
> +        { id: "Users", cols: [usertable, userchart] },
Речь о внешнем виде второй ячейки - комментарий оставлен только для неё
```js
{ id: "Users", rows: [
   userlist,    // here: toolbar with filter input/sorting buttons, list
   userchart
]},
```

2022-07-21 10:40 UTC, LukshaMaria commented on modules/maintable.js
> +    url: "http://localhost/Projects-Webix/data/data.js",
fixed

2022-07-21 17:39 UTC, LukshaMaria commented on modules/usertable.js
> +        view: "datatable",
fixed

2022-07-21 18:06 UTC, LukshaMaria commented on modules/usertable.js
> +        cols: [
fixed

2022-07-21 18:13 UTC, LukshaMaria commented on modules/usertable.js
> +        }
fixed

2022-07-21 18:16 UTC, LukshaMaria commented on modules/charts.js
> +    url: "http://localhost/Projects-Webix/data/users.js",
fixed

2022-07-21 18:16 UTC, LukshaMaria commented on main.js
> +    $$("form1").bind("datatable1");
fixed

2022-07-21 18:16 UTC, LukshaMaria commented on main.js
> +        { id: "Products", cols: [producttable] },
fixed

2022-07-21 18:16 UTC, LukshaMaria commented on main.js
> +    const popup1 = webix.ui({
fixed

2022-07-21 18:17 UTC, LukshaMaria commented on main.js
> +        { id: "Users", cols: [usertable, userchart] },
В задании используется cells

2022-07-21 18:18 UTC, LukshaMaria commented on task-webix.html
> +            background-color: rgb(164, 164, 164);
fixed

2022-07-22 15:49 UTC, LukshaMaria commented on main.js
> +        { id: "Users", cols: [usertable, userchart] },
аа, хорошо, исправлю

2022-07-22 16:05 UTC, LukshaMaria commented on main.js
> +        { id: "Users", cols: [usertable, userchart] },
fixed

2022-07-23 14:17 UTC, HelgaListopad requested changes

2022-07-23 14:17 UTC, HelgaListopad commented on task-webix.html
> +    <script type="text/javascript" src="main.js"></script>
Код вообще не работает - здась скрипт нужно подключать как модуль

2022-07-23 14:21 UTC, HelgaListopad commented on modules/maintable.js
> +       });
Не закрыта скобка => всё приложение падает с ошибкой

2022-07-23 14:22 UTC, HelgaListopad commented on main.js
> +        { id: "Products", cols: [producttable] },
Не совсем (ничего не работает) - оставила отдельный комментарий

2022-07-23 14:28 UTC, HelgaListopad commented on modules/forms.js
> +                        }
Стоит упростить
```js
if (form.validate()) {
   const item_data = form.getValues();
   if (item_data.id) { ... }
   else { ... }
}
```

2022-07-23 14:35 UTC, HelgaListopad commented on modules/maintable.js
> +            this.remove(id);
`return false` нужно вынести из `webix.confirm` (т.е. вернуть на старое место)
Отдельно пометила, что там не закрыта скобка.

В целом в такой записи 
<details><summary>(кликни, чтобы развернуть)</summary>

```js
        "wxi-trash": function (e, id) {
            const list = $$("datatable1");
            webix.confirm("Do you want to delete this item?", "confirm-warning").then(function () {
                list.remove(id);
                return false;
            });
        }
```

</details>
обработчик клика ничего не возвращает (return написан для webix.confirm и никак не используется)
Более того, `confirm` асинхронный (ждёт действия от пользователя, потом вызывается `then`) и никак не прерывает дальнейшие действия, которые выполняются в обработчике клика или после него в коде webix

2022-07-23 14:43 UTC, HelgaListopad requested changes

2022-07-23 14:43 UTC, HelgaListopad commented on modules/usertable.js
> +const usertable =
Это больше не таблица - есть смысл переименовать и переменную (включая импорт/экспорт), и сам файл

2022-07-23 14:43 UTC, HelgaListopad commented on modules/usertable.js
> +                        webix.message("Deleted");
Код после `return false` уже не выполняется

2022-07-23 14:43 UTC, HelgaListopad commented on modules/usertable.js
> +                );
После webix.confirm не хватает return false, чтобы запретить селект по клику на эту иконку

2022-07-23 14:43 UTC, HelgaListopad commented on modules/usertable.js
> +        template:"#name# from #country# <span class='webix_icon mdi mdi-close remove-icon' title='Remove'></span>",
Я бы предложила выровнять иконки по правому краю
В стилях:
```css
.remove-icon {
    float: right;
    margin-top: 5px;
}
```

2022-07-23 14:46 UTC, HelgaListopad commented on modules/maintable.js
> +    }
Через ready вызывать attachEvent несколько излишне
В кофигурации таблицы лучше использовать `on`
```js
on: {
   onAfterSelect(id) { ... }
}
```

2022-07-23 18:11 UTC, LukshaMaria commented on modules/forms.js
> +                        }
Изменения внесены в код.

2022-07-23 18:12 UTC, LukshaMaria commented on modules/maintable.js
> +       });
Скобку } добавила

2022-07-23 18:17 UTC, LukshaMaria commented on modules/maintable.js
> +    }
Изменила ready на on

2022-07-23 18:25 UTC, LukshaMaria commented on modules/usertable.js
> +const usertable =
Изменения внесены в код.

2022-07-23 18:27 UTC, LukshaMaria commented on modules/usertable.js
> +                        webix.message("Deleted");
Изменения внесены в код.

2022-07-23 18:32 UTC, LukshaMaria commented on modules/usertable.js
> +                );
Изменения внесены в код.

2022-07-23 18:34 UTC, LukshaMaria commented on modules/usertable.js
> +        template:"#name# from #country# <span class='webix_icon mdi mdi-close remove-icon' title='Remove'></span>",
Изменения внесены в код.

2022-07-24 14:13 UTC, LukshaMaria commented on task-webix.html
> +    <script type="text/javascript" src="main.js"></script>
Изменения внесены в код

2022-07-24 14:34 UTC, LukshaMaria commented on modules/maintable.js
> +       });
Изменила на стрелочную функцию

2022-07-25 14:11 UTC, HelgaListopad commented on modules/userlist.js
> +                        return false;
Вот этот return лишний

2022-07-25 14:12 UTC, HelgaListopad commented on modules/maintable.js
> +            webix.confirm("Do you want to delete this item?", "confirm-warning").then(() => list.remove(id));
После webix.confirm не хватает return false (т.е. возвращать false нужно из обработчика клика wxi-trash)

2022-07-25 15:06 UTC, LukshaMaria commented on modules/userlist.js
> +                        return false;
fixed

2022-07-25 15:12 UTC, LukshaMaria commented on modules/maintable.js
> +            webix.confirm("Do you want to delete this item?", "confirm-warning").then(() => list.remove(id));
fixed

2022-07-25 15:38 UTC, HelgaListopad approved these changes

2022-07-25 15:38 UTC, merged