modified:   data/products.js
LukshaMaria/Projects-Webix pull request #6
Opened 2022-07-26 20:41 UTC by LukshaMaria

modified:   main.js
modified:   modules/charts.js
modified:   modules/maintable.js
modified:   modules/producttable.js
modified:   modules/userlist.js

2022-08-01 09:48 UTC, HelgaListopad requested changes
В modules\forms.js измени текстовое поле для категорий
```js
{ view: "text", name: "category", label: "Category" },
```
На richselect c опциями из соответствующей коллекции (коллекция - то, что можно и нужно переиспользовать без webix.copy в нескольких виджетах)

2022-08-01 09:48 UTC, HelgaListopad commented on main.js
> +                age: ["age", "sum"]
> let it show the number of users per country. 

Тут нужен count, а не sum

2022-08-01 09:48 UTC, HelgaListopad commented on main.js
> +    $$("datatable1").sync($$(collection));
Нужно убрать 

а) Таблица не должна синхронизироваться с этой коллекцией. Синхронизация предназначена для того, чтобы передавать основной набор данных.
Таблица "datatable1" уже получает данные по `url: "./data/data.js"`, а в `collection`  не те данные.

б) К коллекции не нужно обращаться через `$$`.
Метод нужен для того, чтобы получать UI-элементы, а коллекция у тебя уже создана и доступна через имя переменной (`collection`)

2022-08-01 09:48 UTC, HelgaListopad commented on main.js
> +                else if (filter == 4) return year > 2000;
Для такого случая лучше подойдёт конструкция `switch`

2022-08-01 09:48 UTC, HelgaListopad commented on main.js
> +                return node.getValue();
По смыслу лучше переименовать `node` на `view` 
По логу можно проверить, что в данном случае это tabbar
`registerFilter` позволяет регистрировать как фильтр и HTML-элементы (например, input), и в таком случае было бы `node`, как в документации

2022-08-01 09:48 UTC, HelgaListopad commented on main.js
> +            setValue: function (node, value) {
node => view

2022-08-01 09:48 UTC, HelgaListopad commented on modules/charts.js
>      url: "./data/users.js",
Чарт синхронизирован с листом, поэтому своего собственного источника данных у него не должно быть (это приичина, по которой в чарте отображается слишком много столбиков)

2022-08-01 09:48 UTC, HelgaListopad commented on modules/maintable.js
> +                { id: "category", header: "Category", width: 100 },
Здесь нужно колонке добавить `collection`
```js
{ id: "category", header: "Category", width: 100, collection: collection },

// ES6 позволяет писать вот так, если имя параметра и переменной совпадают
{ id: "category", header: "Category", width: 100, collection },
```

2022-08-01 09:48 UTC, HelgaListopad commented on modules/maintable.js
> +                    obj.category=Math.floor(Math.random()*(max - min) + min);
Можно сократить и сразу подставить числа, не объявляя лишние переменные
По code style - не стоит забывать про отступы и пробелы

2022-08-01 09:48 UTC, HelgaListopad commented on modules/producttable.js
> +    },
а) `rules` - это объект, а в объекте не может быть двух одинаковых ключей
б) есть ли в данных `value` и зачем его валидировать, если редактируется `title` ?

2022-08-01 09:48 UTC, HelgaListopad commented on modules/producttable.js
> +    // ],
а) дерево - это не TreeTable, в нём не будет columns
б) ненужные комментарии из кода стоит убирать

2022-08-01 09:48 UTC, HelgaListopad commented on main.js
> +        });
Синхронизация срабатывает и на сортировку/фильтрацию листа, и при сортировке данные в чарте будут "скакать": группировка срабатывает по тем же критериям, но данные собираются в другом порядке
Чтобы избежать этого эффекта, после группировки к чарту можно применить свою сортировку по одному из имеющихся критериев (age, country)

2022-08-01 11:05 UTC, LukshaMaria commented on main.js
> +                age: ["age", "sum"]
fixed

2022-08-01 19:15 UTC, LukshaMaria commented on modules/charts.js
>      url: "./data/users.js",
fixed

2022-08-01 19:32 UTC, LukshaMaria commented on main.js
> +                else if (filter == 4) return year > 2000;
fixed

2022-08-01 19:44 UTC, LukshaMaria commented on main.js
> +    $$("datatable1").sync($$(collection));
fixed

2022-08-01 19:48 UTC, LukshaMaria commented on main.js
> +                return node.getValue();
fixed

2022-08-01 19:52 UTC, LukshaMaria commented on main.js
> +            setValue: function (node, value) {
fixed

2022-08-01 19:55 UTC, LukshaMaria commented on modules/maintable.js
> +                    obj.category=Math.floor(Math.random()*(max - min) + min);
fixed

2022-08-01 19:58 UTC, LukshaMaria commented on modules/producttable.js
> +    },
title

2022-08-01 20:19 UTC, LukshaMaria commented on modules/maintable.js
> +                { id: "category", header: "Category", width: 100 },
fixed

2022-08-01 20:39 UTC, LukshaMaria commented on modules/producttable.js
> +    // ],
fixed

2022-08-01 20:58 UTC, LukshaMaria commented on modules/producttable.js
> +    },
fixed

2022-08-02 11:59 UTC, HelgaListopad requested changes

2022-08-02 11:59 UTC, HelgaListopad commented on main.js
> +                    case 1: return year;
Фильтрация должна возвращать только boolean

2022-08-02 16:56 UTC, LukshaMaria commented on main.js
> +                    case 1: return year;
fixed, added value "true"

2022-08-05 10:54 UTC, HelgaListopad approved these changes

2022-08-05 10:54 UTC, merged